### ISSUE TITLE
Core check fails after installing the app

### ISSUE THREAD

**Issue by solracsf** [CADViewer/NextCloud#26]
```
# occ integrity:check-core
  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: 94195a260a005dac543c3f6aa504f1b28e0078297fe94a4f52f012c16c109f0323eecc9f767d6949f860dfe454625fcaf1dc56f87bb8350975d8f006bbbdf14a
      - current: d97040bc399114326e7751ee4c39f2ebe102ea6c92972ecf320143fc543afeb82d7b223f120bc7aec55fa3e5cc0faf15eab99c4894b1b3dcf60ccf418d8810ab
  - EXTRA_FILE:
    - core/img/filetypes/dgn.svg:
      - expected:
      - current: 2e4ae9859c70005b895073cdd94cebc48ba89afd50d17ad3e76ab20a7e1ab90e0d6b6e7c85fbfd5b95e442620ea5b36805ff074843bd6d88550dc3b05aa5d559
```
